config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/fair-epos-prototype
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/norwegian-geotechnical-institute/tsunami-inundation-emulator:
      branch: main
      repo: https://github.com/norwegian-geotechnical-institute/tsunami-inundation-emulator
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/norwegian-geotechnical-institute/tsunami-inundation-emulator git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-copper-ray.sh
        container: qc.acc_nerdy-auburn-iguana
  QC.Doc:
    repos:
      github.com/norwegian-geotechnical-institute/tsunami-inundation-emulator find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-mustard-collie.sh
        container: qc.doc_hasty-buff-chihuahua
      github.com/norwegian-geotechnical-institute/tsunami-inundation-emulator git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-tan-mole.sh
        container: qc.doc_bluesy-indigo-chihuahua
      github.com/norwegian-geotechnical-institute/tsunami-inundation-emulator markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-grey-boar.sh
        container: qc.doc_lousy-khaki-tuatara
  QC.Lic:
    repos:
      github.com/norwegian-geotechnical-institute/tsunami-inundation-emulator licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-chestnut-ocelot.sh
        container: qc.lic_gloppy-russet-indri
  QC.Met:
    repos:
      github.com/norwegian-geotechnical-institute/tsunami-inundation-emulator cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-bronze-cuttlefish.sh
        container: qc.met_snappy-myrtle-scorpion
  QC.Ver:
    repos:
      github.com/norwegian-geotechnical-institute/tsunami-inundation-emulator get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-tomato-devil.sh
        container: qc.ver_messy-thistle-dormouse
timeout: 5400
